apiVersion: v1
kind: Service
metadata:
  # 이 서비스의 이름을 my-backend-service로 지정합니다.
  name: dys-backend
spec:
  # LoadBalancer 타입을 사용해 외부 IP 주소를 할당받습니다.
  type: LoadBalancer
  selector:
    # 'app: my-backend' 라벨이 붙은 Pod를 찾아 연결합니다.
    app: dys-backend
  ports:
  - protocol: TCP
    # 외부에서는 80 포트로 접속하면,
    port: 80
    # 컨테이너의 8000 포트(메인 서버)로 연결해줍니다.
    targetPort: 8000
  - protocol: TCP
    # 외부에서는 8001 포트로 접속하면,
    port: 8001
    # 컨테이너의 8001 포트(WebSocket 서버)로 연결해줍니다.
    targetPort: 8001